### ISSUE TITLE
Double topic velocity

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/ros_robot_teleoperation#2]
I see in https://github.com/officinerobotiche/ros_robot_teleoperation/blob/feature/reneame_cmd_vel/src/keybrd_teleop/src/teleop_key.cpp#L20

A couple of topic to send Twist message:

``` c
mVelPub = m_nh.advertise<geometry_msgs::Twist>("/cmd_vel", 10);
mPubVelControl = m_nh.advertise<geometry_msgs::Twist>("/" + robot + "/" + cmd_vel, 10);
```

Why do you use this couple of twist topic?

**Comment by rbonghi** [comment]
In according with https://github.com/officinerobotiche/ros_serial_bridge/issues/18

I will remove the first publisher:

``` c
mVelPub = m_nh.advertise<geometry_msgs::Twist>("/cmd_vel", 10);
```

**Comment by Myzhar** [comment]
Solved and closed
